// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8yOALhcpFTLRgnGBk7g-Y-1kwlSRKdk',
    appId: '1:16466423402:web:01d804166e61affd57e413',
    messagingSenderId: '16466423402',
    projectId: 'trackmark1-83fb3',
    authDomain: 'trackmark1-83fb3.firebaseapp.com',
    storageBucket: 'trackmark1-83fb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1YaI-QxSXxtLZ7r556Oc2Mb41h5THHo',
    appId: '1:16466423402:android:0152067ad45bfc4457e413',
    messagingSenderId: '16466423402',
    projectId: 'trackmark1-83fb3',
    storageBucket: 'trackmark1-83fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04GvdRGcHsRxkGg0yTy102gcAOIfwAHk',
    appId: '1:16466423402:ios:a78c63fa2df97a4257e413',
    messagingSenderId: '16466423402',
    projectId: 'trackmark1-83fb3',
    storageBucket: 'trackmark1-83fb3.firebasestorage.app',
    iosBundleId: 'com.example.trackmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04GvdRGcHsRxkGg0yTy102gcAOIfwAHk',
    appId: '1:16466423402:ios:a78c63fa2df97a4257e413',
    messagingSenderId: '16466423402',
    projectId: 'trackmark1-83fb3',
    storageBucket: 'trackmark1-83fb3.firebasestorage.app',
    iosBundleId: 'com.example.trackmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC8yOALhcpFTLRgnGBk7g-Y-1kwlSRKdk',
    appId: '1:16466423402:web:026479ab2134630f57e413',
    messagingSenderId: '16466423402',
    projectId: 'trackmark1-83fb3',
    authDomain: 'trackmark1-83fb3.firebaseapp.com',
    storageBucket: 'trackmark1-83fb3.firebasestorage.app',
  );
}
